# Generated by Django 3.0.6 on 2020-05-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_finder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='kupsko',
        ),
    ]
