# Generated by Django 3.0.6 on 2020-05-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_finder', '0003_auto_20200529_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
