# Generated by Django 3.0.6 on 2020-05-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_finder', '0004_remove_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
