# Generated by Django 3.0.6 on 2020-05-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_finder', '0005_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Warsaw', max_length=50),
        ),
    ]
