# Generated by Django 3.0.6 on 2020-05-31 22:19

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_finder', '0006_auto_20200531_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
