# Generated by Django 3.0.6 on 2020-06-01 10:02

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_finder', '0007_profile_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favourite',
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite', django_mysql.models.JSONField(default=dict)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_finder.Profile')),
            ],
        ),
    ]
