# Generated by Django 3.0.6 on 2020-06-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_finder', '0008_auto_20200601_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='favourite',
            new_name='test',
        ),
    ]
