# Generated by Django 3.0.6 on 2020-06-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_finder', '0009_auto_20200601_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='test',
            new_name='my_favourite',
        ),
    ]
