# Generated by Django 3.0.6 on 2020-06-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_finder', '0011_places_rejected'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
    ]
