# Generated by Django 3.0.6 on 2020-06-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_finder', '0013_auto_20200602_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejected',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
        migrations.DeleteModel(
            name='Rejected',
        ),
    ]
