# Generated by Django 3.0.6 on 2020-06-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_finder', '0014_auto_20200602_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='choose_value',
            field=models.IntegerField(default=0),
        ),
    ]
