# Generated by Django 3.0.6 on 2020-06-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_finder', '0016_auto_20200602_1739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Favourites',
        ),
        migrations.RenameModel(
            old_name='Favourite',
            new_name='Places',
        ),
        migrations.RenameField(
            model_name='favourites',
            old_name='my_place',
            new_name='my_favourites',
        ),
        migrations.RenameField(
            model_name='places',
            old_name='my_favourite',
            new_name='my_places',
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Warsaw', max_length=100),
        ),
    ]
